name: Frontend Lint and Auto Merge dev-to-main

on:
  push:
    branches:
      - dev

jobs:
  # Step 1 - Code Linting (Quality Check)
  # Perform Static Code Analysis
  lint-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Validate HTML and CSS using HTMLProofer
        uses: anishathalye/proof-html@v2.1.2
        with:
          directory: "./"
          check_html: true
          check_css: true

      - name: Validate JavaScript by running ESLint
        uses: iCrawl/action-eslint@v1
        with:
          custom-glob: "./Js/**/*.js"
                        
  # Step 2 - Merge to Main
  # Conditional auto-merge to Main
  auto-merge-to-main:
    runs-on: ubuntu-latest
    needs: lint-check
    if: github.ref == 'refs/heads/dev'
    steps:
      - name: Await manual confirmation
        uses: trstringer/manual-approval@v1
        with:
          approvers: ""
          secret: ${{secrets.GITHUB_TOKEN}}

      # Merge dev branch into main branch
      - name: Merge dev into main
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/dev' }}
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git remote set-url origin http://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git checkout main
          git merge dev
          git push origin main